CREATE TABLE TEAM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    MONEY NUMERIC(10, 2) DEFAULT 0.00,
    PERCENT NUMERIC(5, 2) DEFAULT 0.00
);

INSERT INTO TEAM (NAME, MONEY, PERCENT) VALUES
    ('Team A', 500000.00, 5.00),
    ('Team B', 300000.00, 3.50),
    ('Team C', 700000.00, 7.25);

CREATE TABLE PLAYER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    AGE INT NOT NULL,
    POSITION VARCHAR(50) NOT NULL,
    EXPERIENCE INT NOT NULL,
    TEAM_ID INT,
    CONSTRAINT FK_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID)
);

INSERT INTO PLAYER (NAME, AGE, POSITION, EXPERIENCE, TEAM_ID) VALUES
    ('Lionel Messi', 36, 'Forward', 200, 1),
    ('Kevin De Bruyne', 32, 'Midfielder', 150, 2),
    ('Virgil van Dijk', 32, 'Defender', 120, 1),
    ('Cristiano Ronaldo', 38, 'Forward', 250, 3),
    ('Erling Haaland', 23, 'Forward', 50, 2);
